export const ACTION_INIT_CURRENCIES = 'INIT_CURRENCIES';
export const ACTION_SELECTED_CURRENCY = 'SELECTED_CURRENCY';
export const ACTION_SET_DEFAULT_CURRENCY = 'SET_DEFAULT_CURRENCY';
export const ACTION_ADD_WAITING_PRODUCT = 'ADD_WAITING_PRODUCT';
export const ACTION_REMOVE_WAITING_PRODUCT = 'REMOVE_WAITING_PRODUCT';
export const ACTION_ADD_ARCHIVE_PRODUCT = 'ADD_ARCHIVE_PRODUCT';
export const ACTION_REMOVE_ARCHIVE_PRODUCT = 'REMOVE_ARCHIVE_PRODUCT';

